config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  resources :questions do
      resources :comments, only: [:create]
      resource :voqte, only: [:create, :destroy]
      resources :answers, only: [:create]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  body        :text
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  body        :text
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_many :voqtes
  has_many :answers

  def voqted_by?(user)
    voqtes.exists?(user: user)
  end

  validates :title, presence: true
  validates :description, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :comments
  has_many :answers
end

app/models/voqte.rb
# == Schema Information
#
# Table name: voqtes
#
#  id          :integer          not null, primary key
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Voqte < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    question.answers.create(answers_params)

    redirect_to question
  end

  private
    def answers_params
      params.require(:answer).permit(:body).merge(user: current_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    question.comments.create(comments_params)
    redirect_to question
  end

  def comments_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show ]

  def index
    @question = Question.all
  end

  def new
    @question = Question.new
  end


  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to root_path, notice: "Pregunta publicada con exito"
    else
      render :new
    end
  end


  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to root_path, notice: "Pregunta actualizada correctamente"
    else
      render :edit
    end
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to root_path, notice:"Pregunta eliminada con exito"
  end


  private
    def question_params
      params.require(:question).permit(:title, :description)
    end

end

app/controllers/voqtes_controller.rb
class VoqtesController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    question.voqtes.create(user: current_user)

    redirect_to :back
  end

  def destroy
    question = Question.find(params[:question_id])
    question.voqtes.where(user: current_user).take.try(:destroy)
    redirect_to :back

  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_title
    @question.new_record? ? "Publicar Pregunta" : "Modificar Pregunta"
  end
end

app/helpers/voqtes_helper.rb
module VoqtesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "FlowOverStack" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

  <div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FlowOverStack", root_path, class:"navbar-brand" %>
      <div class="navbar-collapse collapse navbar-responsive-collapse navbar-right">
        <ul class="nav navbar-nav navbar-right">
          <%if user_signed_in?%>
              <li>
            <a href="#">
              <%= current_user.email %></a>
            </li>
            <li>
              <%= link_to "Salir", destroy_user_session_path, method: :delete  %>
            </li>
            <% else %>
            <li>
              <%= link_to "Registrarse", new_user_registration_path%>
            </li>
            <li>
              <%= link_to "Ingresar", new_user_session_path %>
            </li>
            <% end %>
            <li><a href="#">
              <input type="text" class="" placeholder="Search"></a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; ja7rodal 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
  </html>

app/views/questions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <h2><%= form_title %></h2>
      <% if @question.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= form_for @question do |f|%>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control input-lg", placeholder: "Titulo" %>
      </div>

      <div class="form-group">
        <%= f.text_area :description, class:"form-control input-lg", placeholder: "Pregunta...", size: "60x12" %>
      </div>

      <div class="form-group">
        <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <h1>Questions</h1>
    <div class="text-right">
      <%= link_to "Hacer Preguntar", new_question_path ,class:"btn btn-success" %>
    </div>
    <% @question.each do |question| %>
    <div class="row">
      <hr>
    <div class="col-xs-1">
      <p class="text-center">
      <%if user_signed_in? %>
        <% if question.voqted_by? current_user %>
          <%= link_to question_voqte_path(question), method: :delete, clase:"" do %>
            <span class="caret"></span>
          <% end %>
        <% else %>
          <%= link_to question_voqte_path(question), method: :post, class: "" do %>
            <span class="dropup"><span class="caret"></span></span>

          <% end %>
        <% end %>
      <% end %>
      <%= question.voqtes.count %></p>
      <p class="text-center">Votos</p>
    </div>
    <div class="col-xs-1">
      <p class="text-center"><%= question.comments.count %></p>
      <p class="text-center">Respuestas</p>
    </div>
    <div class="col-xs-8 ">
      <div><%= link_to question.title, question_path(question), class:"Pregunta"  %></div>
      <p>Preguntó <%= question.user.email %> hace <%= question.created_at  %></p>
      <% if user_signed_in? && question.user == current_user %>
      <div class="actions text-rigth">
        <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_question_path(question) %>
        <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, question, method: :delete, data: { confirm: "¿Estás seguro de eliminar este questiono?" } %>
      </div>
      <% end %>
      </div>
    </div><!--col-10  -->
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h2>Nueva Pregunta</h2>
<%= form_for @question do |f|%>
  <div class="form-group">
      <%= f.text_field :title, class: "", placeholder: "Titulo" %>
  </div>

  <div class="form-group">
      <%= f.text_area :description, class:"", placeholder: "Pregunta...", size: "60x12" %>
  </div>

  <div class="form-group">
      <%= f.submit "Publicar Pregunta", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><%= @question.title %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1">
      <p class="text-center">
        <%if user_signed_in? %>
          <% if @question.voqted_by? current_user %>
            <%= link_to question_voqte_path(@question), method: :delete, clase:"" do %>
              <span class="caret"></span>
            <% end %>
          <% else %>
            <%= link_to question_voqte_path(@question), method: :post, class: "" do %>
              <span class="dropup"><span class="caret"></span></span>
            <% end %>
          <% end %>
        <% end %>
      </p>
      <p class="text-center"><%= @question.voqtes.count %></p>
    </div>
    <div class="col-xs-10">
      <p><%= @question.description%></p>
    </div>
  </div>
  <div class="row">
      <div class="col-xs-9 col-xs-offset-1">
        <% @question.comments.each do |comment| %>
          <div class="panel panel-default">
            <div class="panel-body"><%= comment.user.email %> <%= comment.created_at%>
              <p><%= comment.body %></p></div>
          </div>
          <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-9 col-xs-offset-1">
        <% if signed_in? %>
          <%= form_for [@question, @question.comments.build] do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
          </div>
          <div class="actions text-right">
            <%= f.submit "Comentar", class: "btn btn-info" %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-9 col-xs-offset-2">
          <h3>Respuestas</h3>
          <hr>
          <% @question.answers.each do |answer| %>
            <div class="panel panel-default">
              <header class="panel-heading">Respondio <%= answer.user.email %></header>
              <div class="panel-body"><%= answer.body %></div>
            </div>
          <% end %>
          <% if user_signed_in? %>

            <%= form_for [@question , @question.answers.build] do |f| %>
              <div class="form-group">
                <%= f.text_area :body, class:"form-control",size:"60x12", placeholder: "Tú respuesta..." %>
              </div>

              <div class="text-right">
                <%= f.submit "Responder", class:"btn btn-primary" %>
              </div>
            <% end %>
          <% end %>
      </div>

    </div>

  </div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>